export * from './HomePage'
export * from './ProductsPage'
export * from './ProductPage'
export * from './CartPage'
export * from './RegisterPage'
export * from './LoginPage' 
export * from './OrderPage'
export * from './CheckoutPage'